version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
